Repository dnsimple/dns_erlang, pull requests merged in 2025-05, with the labels that each got.

#74 fix: add back the reserved space for optrr
  src/dns.erl
Labels: bug

#75 Update update_deps in CI for erlang
  .github/workflows/check_deps.yml
Labels: dependencies

#28 Escape backslashes too
  src/dns.erl
  test/dns_test.erl
Labels: bug

#29 Catch messages with missing additional sections
  src/dns.erl
  test/dns_test.erl
Labels: bug

#72 Rewrite most of the encode/decode logic
  .github/workflows/ci.yml
  .gitignore
  include/dns.hrl
  include/dns_records.hrl
  rebar.config
  src/dns.erl
  src/dns_decode.erl
  src/dns_encode.erl
  src/dns_names.erl
  src/dns_record.erl
  src/dns_record_info.erl
  src/dns_tsig.erl
  src/dnssec.erl
  test/dns_names_test.erl
  test/dns_record_test.erl
  test/dns_test.erl
  test/dns_tsig_test.erl
  test/dnssec_test.erl
Labels: enhancement

#76 Add OTP28 to CI
  .github/workflows/ci.yml
Labels: dependencies
